name: Deploy to GitHub Pages

on:
  push:
    branch: [master]
    paths:
      - "src/index.html"
      - "src/styles.css"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub Pages
        uses: actions/setup-pages@v3

      - name: Deploy to GitHub Pages
        run: |
          mkdir public
          cp src/index.html public/index.html  # Copy the index.html from src
          cp src/styles.css public/styles.css  # Copy the styles.css from src
          touch public/.nojekyll  # Avoid Jekyll processing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
